In [323]:
import numpy as np
import pandas as pd

In [324]:
train_dataset = 'Bus_Fare_Dataset.csv'
test_dataset = 'Bus_Fare_Dataset.csv'

In [325]:
train_df = pd.read_csv(train_dataset)
test_df = pd.read_csv(test_dataset)

In [326]:
print(train_df)
print('#####################################################################')
print(test_df)

    Distance (km) Air Conditioned Television   Food Service    Bus Fare
0             307             Yes        Yes      Available  Affordable
1             491             Yes        Yes  Not Available  Affordable
2             327              No        Yes      Available     Premium
3             285             Yes        Yes      Available     Premium
4             400              No        Yes  Not Available  Affordable
5             412              No         No      Available     Premium
6             393             Yes        Yes  Not Available     Premium
7              86              No         No  Not Available      Budget
8             465              No         No  Not Available      Luxury
9             349              No        Yes  Not Available      Budget
10            417             Yes        Yes      Available     Premium
11            448              No         No      Available      Budget
12            238             Yes        Yes      Available     Premium
13            370             Yes        Yes      Available      Budget
14            367             Yes        Yes  Not Available      Luxury
15             63              No         No      Available      Budget
16            115             Yes         No      Available      Luxury
17            214              No         No  Not Available      Luxury
18            431              No        Yes      Available      Luxury
19            302             Yes        Yes      Available      Luxury
20            433              No         No  Not Available      Luxury
21            166              No         No      Available      Budget
22            111              No         No  Not Available     Premium
23            408             Yes        Yes      Available      Budget
24            346             Yes         No  Not Available  Affordable
25            370              No        Yes  Not Available     Premium
26            442              No        Yes      Available     Premium
27            358              No         No      Available     Premium
28             54              No         No  Not Available      Luxury
29            432              No        Yes  Not Available     Premium
30            374             Yes         No      Available  Affordable
31            472              No         No  Not Available  Affordable
32             55              No         No  Not Available      Budget
33             61              No        Yes  Not Available      Budget
34            450             Yes        Yes      Available      Budget
35             74              No        Yes      Available  Affordable
36            336             Yes        Yes  Not Available      Luxury
37             55             Yes         No  Not Available      Luxury
38            347              No        Yes  Not Available     Premium
39            452             Yes        Yes      Available  Affordable
40            107             Yes         No  Not Available  Affordable
41            169             Yes        Yes  Not Available     Premium
42            280             Yes         No  Not Available      Luxury
43            181             Yes        Yes  Not Available      Luxury
44            294             Yes         No      Available     Premium
45            382              No         No  Not Available      Luxury
46            330              No         No  Not Available      Budget
47            404              No         No  Not Available      Budget
48            365              No         No      Available      Budget
49            102             Yes        Yes  Not Available     Premium
#####################################################################
    Distance (km) Air Conditioned Television   Food Service    Bus Fare
0             307             Yes        Yes      Available  Affordable
1             491             Yes        Yes  Not Available  Affordable
2             327              No        Yes      Available     Premium
3             285             Yes        Yes      Available     Premium
4             400              No        Yes  Not Available  Affordable
5             412              No         No      Available     Premium
6             393             Yes        Yes  Not Available     Premium
7              86              No         No  Not Available      Budget
8             465              No         No  Not Available      Luxury
9             349              No        Yes  Not Available      Budget
10            417             Yes        Yes      Available     Premium
11            448              No         No      Available      Budget
12            238             Yes        Yes      Available     Premium
13            370             Yes        Yes      Available      Budget
14            367             Yes        Yes  Not Available      Luxury
15             63              No         No      Available      Budget
16            115             Yes         No      Available      Luxury
17            214              No         No  Not Available      Luxury
18            431              No        Yes      Available      Luxury
19            302             Yes        Yes      Available      Luxury
20            433              No         No  Not Available      Luxury
21            166              No         No      Available      Budget
22            111              No         No  Not Available     Premium
23            408             Yes        Yes      Available      Budget
24            346             Yes         No  Not Available  Affordable
25            370              No        Yes  Not Available     Premium
26            442              No        Yes      Available     Premium
27            358              No         No      Available     Premium
28             54              No         No  Not Available      Luxury
29            432              No        Yes  Not Available     Premium
30            374             Yes         No      Available  Affordable
31            472              No         No  Not Available  Affordable
32             55              No         No  Not Available      Budget
33             61              No        Yes  Not Available      Budget
34            450             Yes        Yes      Available      Budget
35             74              No        Yes      Available  Affordable
36            336             Yes        Yes  Not Available      Luxury
37             55             Yes         No  Not Available      Luxury
38            347              No        Yes  Not Available     Premium
39            452             Yes        Yes      Available  Affordable
40            107             Yes         No  Not Available  Affordable
41            169             Yes        Yes  Not Available     Premium
42            280             Yes         No  Not Available      Luxury
43            181             Yes        Yes  Not Available      Luxury
44            294             Yes         No      Available     Premium
45            382              No         No  Not Available      Luxury
46            330              No         No  Not Available      Budget
47            404              No         No  Not Available      Budget
48            365              No         No      Available      Budget
49            102             Yes        Yes  Not Available     Premium

In [327]:
train_df = train_df.to_numpy()
test_df = test_df.to_numpy()
record = np.array(test_df)

train_df[np.where(train_df=='Yes')] = 1
train_df[np.where(train_df=='No')] = 0

test_df[np.where(test_df=='Yes')] = 1
test_df[np.where(test_df=='No')] = 0

train_df[np.where(train_df=='Available')] = 1
train_df[np.where(train_df=='Not Available')] = 0

test_df[np.where(test_df=='Available')] = 1
test_df[np.where(test_df=='Not Available')] = 0

train_df[np.where(train_df=='Budget')] = 0
train_df[np.where(train_df=='Affordable')] = 1
train_df[np.where(train_df=='Premium')] = 2
train_df[np.where(train_df=='Luxury')] = 3

test_df[np.where(test_df=='Budget')] = 0
test_df[np.where(test_df=='Affordable')] = 1
test_df[np.where(test_df=='Premium')] = 2
test_df[np.where(test_df=='Luxury')] = 3

print(train_df)
print('#####################################################################')
print(test_df)

[[307 1 1 1 1]
 [491 1 1 0 1]
 [327 0 1 1 2]
 [285 1 1 1 2]
 [400 0 1 0 1]
 [412 0 0 1 2]
 [393 1 1 0 2]
 [86 0 0 0 0]
 [465 0 0 0 3]
 [349 0 1 0 0]
 [417 1 1 1 2]
 [448 0 0 1 0]
 [238 1 1 1 2]
 [370 1 1 1 0]
 [367 1 1 0 3]
 [63 0 0 1 0]
 [115 1 0 1 3]
 [214 0 0 0 3]
 [431 0 1 1 3]
 [302 1 1 1 3]
 [433 0 0 0 3]
 [166 0 0 1 0]
 [111 0 0 0 2]
 [408 1 1 1 0]
 [346 1 0 0 1]
 [370 0 1 0 2]
 [442 0 1 1 2]
 [358 0 0 1 2]
 [54 0 0 0 3]
 [432 0 1 0 2]
 [374 1 0 1 1]
 [472 0 0 0 1]
 [55 0 0 0 0]
 [61 0 1 0 0]
 [450 1 1 1 0]
 [74 0 1 1 1]
 [336 1 1 0 3]
 [55 1 0 0 3]
 [347 0 1 0 2]
 [452 1 1 1 1]
 [107 1 0 0 1]
 [169 1 1 0 2]
 [280 1 0 0 3]
 [181 1 1 0 3]
 [294 1 0 1 2]
 [382 0 0 0 3]
 [330 0 0 0 0]
 [404 0 0 0 0]
 [365 0 0 1 0]
 [102 1 1 0 2]]
#####################################################################
[[307 1 1 1 1]
 [491 1 1 0 1]
 [327 0 1 1 2]
 [285 1 1 1 2]
 [400 0 1 0 1]
 [412 0 0 1 2]
 [393 1 1 0 2]
 [86 0 0 0 0]
 [465 0 0 0 3]
 [349 0 1 0 0]
 [417 1 1 1 2]
 [448 0 0 1 0]
 [238 1 1 1 2]
 [370 1 1 1 0]
 [367 1 1 0 3]
 [63 0 0 1 0]
 [115 1 0 1 3]
 [214 0 0 0 3]
 [431 0 1 1 3]
 [302 1 1 1 3]
 [433 0 0 0 3]
 [166 0 0 1 0]
 [111 0 0 0 2]
 [408 1 1 1 0]
 [346 1 0 0 1]
 [370 0 1 0 2]
 [442 0 1 1 2]
 [358 0 0 1 2]
 [54 0 0 0 3]
 [432 0 1 0 2]
 [374 1 0 1 1]
 [472 0 0 0 1]
 [55 0 0 0 0]
 [61 0 1 0 0]
 [450 1 1 1 0]
 [74 0 1 1 1]
 [336 1 1 0 3]
 [55 1 0 0 3]
 [347 0 1 0 2]
 [452 1 1 1 1]
 [107 1 0 0 1]
 [169 1 1 0 2]
 [280 1 0 0 3]
 [181 1 1 0 3]
 [294 1 0 1 2]
 [382 0 0 0 3]
 [330 0 0 0 0]
 [404 0 0 0 0]
 [365 0 0 1 0]
 [102 1 1 0 2]]

In [328]:
train_x=train_df[:, 0:4]
print(train_x)

[[307 1 1 1]
 [491 1 1 0]
 [327 0 1 1]
 [285 1 1 1]
 [400 0 1 0]
 [412 0 0 1]
 [393 1 1 0]
 [86 0 0 0]
 [465 0 0 0]
 [349 0 1 0]
 [417 1 1 1]
 [448 0 0 1]
 [238 1 1 1]
 [370 1 1 1]
 [367 1 1 0]
 [63 0 0 1]
 [115 1 0 1]
 [214 0 0 0]
 [431 0 1 1]
 [302 1 1 1]
 [433 0 0 0]
 [166 0 0 1]
 [111 0 0 0]
 [408 1 1 1]
 [346 1 0 0]
 [370 0 1 0]
 [442 0 1 1]
 [358 0 0 1]
 [54 0 0 0]
 [432 0 1 0]
 [374 1 0 1]
 [472 0 0 0]
 [55 0 0 0]
 [61 0 1 0]
 [450 1 1 1]
 [74 0 1 1]
 [336 1 1 0]
 [55 1 0 0]
 [347 0 1 0]
 [452 1 1 1]
 [107 1 0 0]
 [169 1 1 0]
 [280 1 0 0]
 [181 1 1 0]
 [294 1 0 1]
 [382 0 0 0]
 [330 0 0 0]
 [404 0 0 0]
 [365 0 0 1]
 [102 1 1 0]]

In [329]:
train_y=train_df[:,4]
print(train_y)

[1 1 2 2 1 2 2 0 3 0 2 0 2 0 3 0 3 3 3 3 3 0 2 0 1 2 2 2 3 2 1 1 0 0 0 1 3
 3 2 1 1 2 3 3 2 3 0 0 0 2]

In [330]:
def eucledianDistance(x1,x2):
    distance = (x1[0]-x2[0])**2+(x1[1]-x2[1])**2+(x1[2]-x2[2])**2+(x1[3]-x2[3])**2
    distance = distance**0.5
    return distance

In [331]:
print(eucledianDistance(train_x[0], train_x[0]))
print(eucledianDistance(train_x[0], train_x[7]))

0.0
221.00678722609402

In [332]:
test_x = test_df[:, 0:4]
test_y = test_df[:, 4] # lebel

In [333]:
correct_predictions = []

for i in range(len(test_x)):

    x_test = test_x[i]
    y_test = test_y[i]

    distances=[]

    for i in train_x:
        d = eucledianDistance(i,x_test)
        distances.append(d)

    distances= np.asarray(distances)
    # print(distances)

    k = 3
    sortedDistances = np.argsort(distances)
    # print(sortedDistances)

    sortedDistancs = sortedDistances[0:k]
    # print(sortedDistancs)

    poll = dict()
    poll[0]=0 # voting poll for Budget
    poll[1]=0 # voting poll for Affordable
    poll[2]=0 # voting poll for Premium
    poll[3]=0 # voting poll for Luxury

    for i in sortedDistancs:
        label = train_y[i]
        poll[label]=poll[label]+1

    result = max(poll)

    # if(result==0):
    #     print('Budget')
    # elif(result==1):
    #     print('Affordable')
    # elif(result==2):
    #     print('Premium')
    # else:
    #     print('Luxury')

    # now i have to check if the prediction was right
    # print(result)
    # print(y_test)
    # print(record[0, :])
    if result == y_test:
        # print('True')
        correct_predictions.append(record[i, :])

In [334]:
print(f'Total correct predictions: {len(correct_predictions)}/{len(test_x)}\n')
print('Correct Prediction rows: ')
for i in correct_predictions:
    print(i)

Total correct predictions: 13/50

Correct Prediction rows:
[452 'Yes' 'Yes' 'Available' 'Affordable']
[370 'No' 'Yes' 'Not Available' 'Premium']
[107 'Yes' 'No' 'Not Available' 'Affordable']
[181 'Yes' 'Yes' 'Not Available' 'Luxury']
[433 'No' 'No' 'Not Available' 'Luxury']
[294 'Yes' 'No' 'Available' 'Premium']
[431 'No' 'Yes' 'Available' 'Luxury']
[55 'Yes' 'No' 'Not Available' 'Luxury']
[327 'No' 'Yes' 'Available' 'Premium']
[54 'No' 'No' 'Not Available' 'Luxury']
[294 'Yes' 'No' 'Available' 'Premium']
[166 'No' 'No' 'Available' 'Budget']
[393 'Yes' 'Yes' 'Not Available' 'Premium']